
package cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ValidaCPFService", targetNamespace = "http://control/", wsdlLocation = "http://localhost:10000/validacpf?wsdl")
public class ValidaCPFService
    extends Service
{

    private final static URL VALIDACPFSERVICE_WSDL_LOCATION;
    private final static WebServiceException VALIDACPFSERVICE_EXCEPTION;
    private final static QName VALIDACPFSERVICE_QNAME = new QName("http://control/", "ValidaCPFService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10000/validacpf?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VALIDACPFSERVICE_WSDL_LOCATION = url;
        VALIDACPFSERVICE_EXCEPTION = e;
    }

    public ValidaCPFService() {
        super(__getWsdlLocation(), VALIDACPFSERVICE_QNAME);
    }

    public ValidaCPFService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALIDACPFSERVICE_QNAME, features);
    }

    public ValidaCPFService(URL wsdlLocation) {
        super(wsdlLocation, VALIDACPFSERVICE_QNAME);
    }

    public ValidaCPFService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALIDACPFSERVICE_QNAME, features);
    }

    public ValidaCPFService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidaCPFService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ValidaCPF
     */
    @WebEndpoint(name = "ValidaCPFPort")
    public ValidaCPF getValidaCPFPort() {
        return super.getPort(new QName("http://control/", "ValidaCPFPort"), ValidaCPF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidaCPF
     */
    @WebEndpoint(name = "ValidaCPFPort")
    public ValidaCPF getValidaCPFPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://control/", "ValidaCPFPort"), ValidaCPF.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDACPFSERVICE_EXCEPTION!= null) {
            throw VALIDACPFSERVICE_EXCEPTION;
        }
        return VALIDACPFSERVICE_WSDL_LOCATION;
    }

}
