
package cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ValidaCPF", targetNamespace = "http://control/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ValidaCPF {


    /**
     * 
     * @param cpf
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isCPF", targetNamespace = "http://control/", className = "cliente.IsCPF")
    @ResponseWrapper(localName = "isCPFResponse", targetNamespace = "http://control/", className = "cliente.IsCPFResponse")
    @Action(input = "http://control/ValidaCPF/isCPFRequest", output = "http://control/ValidaCPF/isCPFResponse")
    public String isCPF(
        @WebParam(name = "cpf", targetNamespace = "")
        String cpf);

}
